//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace netOnvifCore.ActionEngine
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.onvif.org/ver10/actionengine/wsdl", ConfigurationName="netOnvifCore.ActionEngine.ActionEnginePort")]
    public interface ActionEnginePort
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.onvif.org/ver10/actionengine/wsdl/GetSupportedActions", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="SupportedActions")]
        System.Threading.Tasks.Task<netOnvifCore.ActionEngine.SupportedActions> GetSupportedActionsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.onvif.org/ver10/actionengine/wsdl/GetActions", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<netOnvifCore.ActionEngine.GetActionsResponse> GetActionsAsync(netOnvifCore.ActionEngine.GetActionsRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.onvif.org/ver10/actionengine/wsdl/CreateActions", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<netOnvifCore.ActionEngine.CreateActionsResponse> CreateActionsAsync(netOnvifCore.ActionEngine.CreateActionsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.onvif.org/ver10/actionengine/wsdl/DeleteActions", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<netOnvifCore.ActionEngine.DeleteActionsResponse> DeleteActionsAsync(netOnvifCore.ActionEngine.DeleteActionsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.onvif.org/ver10/actionengine/wsdl/ModifyActions", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<netOnvifCore.ActionEngine.ModifyActionsResponse> ModifyActionsAsync(netOnvifCore.ActionEngine.ModifyActionsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.onvif.org/ver10/actionengine/wsdl/GetServiceCapabilities", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="Capabilities")]
        System.Threading.Tasks.Task<netOnvifCore.ActionEngine.ActionEngineCapabilities> GetServiceCapabilitiesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.onvif.org/ver10/actionengine/wsdl/GetActionTriggers", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<netOnvifCore.ActionEngine.GetActionTriggersResponse> GetActionTriggersAsync(netOnvifCore.ActionEngine.GetActionTriggersRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.onvif.org/ver10/actionengine/wsdl/CreateActionTriggers", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<netOnvifCore.ActionEngine.CreateActionTriggersResponse> CreateActionTriggersAsync(netOnvifCore.ActionEngine.CreateActionTriggersRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.onvif.org/ver10/actionengine/wsdl/DeleteActionTriggers", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<netOnvifCore.ActionEngine.DeleteActionTriggersResponse> DeleteActionTriggersAsync(netOnvifCore.ActionEngine.DeleteActionTriggersRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.onvif.org/ver10/actionengine/wsdl/ModifyActionTriggers", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<netOnvifCore.ActionEngine.ModifyActionTriggersResponse> ModifyActionTriggersAsync(netOnvifCore.ActionEngine.ModifyActionTriggersRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.onvif.org/ver10/actionengine/wsdl")]
    public partial class SupportedActions
    {
        
        private string[] actionContentSchemaLocationField;
        
        private ActionConfigDescription[] actionDescriptionField;
        
        private SupportedActionsExtension extensionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ActionContentSchemaLocation", DataType="anyURI", Order=0)]
        public string[] ActionContentSchemaLocation
        {
            get
            {
                return this.actionContentSchemaLocationField;
            }
            set
            {
                this.actionContentSchemaLocationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ActionDescription", Order=1)]
        public ActionConfigDescription[] ActionDescription
        {
            get
            {
                return this.actionDescriptionField;
            }
            set
            {
                this.actionDescriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public SupportedActionsExtension Extension
        {
            get
            {
                return this.extensionField;
            }
            set
            {
                this.extensionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.onvif.org/ver10/actionengine/wsdl")]
    public partial class ActionConfigDescription
    {
        
        private ItemListDescription parameterDescriptionField;
        
        private System.Xml.XmlQualifiedName nameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public ItemListDescription ParameterDescription
        {
            get
            {
                return this.parameterDescriptionField;
            }
            set
            {
                this.parameterDescriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.Xml.XmlQualifiedName Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.onvif.org/ver10/schema")]
    public partial class ItemListDescription
    {
        
        private ItemListDescriptionSimpleItemDescription[] simpleItemDescriptionField;
        
        private ItemListDescriptionElementItemDescription[] elementItemDescriptionField;
        
        private ItemListDescriptionExtension extensionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("SimpleItemDescription", Order=0)]
        public ItemListDescriptionSimpleItemDescription[] SimpleItemDescription
        {
            get
            {
                return this.simpleItemDescriptionField;
            }
            set
            {
                this.simpleItemDescriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ElementItemDescription", Order=1)]
        public ItemListDescriptionElementItemDescription[] ElementItemDescription
        {
            get
            {
                return this.elementItemDescriptionField;
            }
            set
            {
                this.elementItemDescriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public ItemListDescriptionExtension Extension
        {
            get
            {
                return this.extensionField;
            }
            set
            {
                this.extensionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.onvif.org/ver10/schema")]
    public partial class ItemListDescriptionSimpleItemDescription
    {
        
        private string nameField;
        
        private System.Xml.XmlQualifiedName typeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.Xml.XmlQualifiedName Type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.onvif.org/ver10/actionengine/wsdl")]
    public partial class ActionTriggerConfigurationExtension
    {
        
        private System.Xml.XmlElement[] anyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Order=0)]
        public System.Xml.XmlElement[] Any
        {
            get
            {
                return this.anyField;
            }
            set
            {
                this.anyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://docs.oasis-open.org/wsn/b-2")]
    public partial class QueryExpressionType
    {
        
        private System.Xml.XmlNode[] anyField;
        
        private string dialectField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        [System.Xml.Serialization.XmlAnyElementAttribute(Order=0)]
        public System.Xml.XmlNode[] Any
        {
            get
            {
                return this.anyField;
            }
            set
            {
                this.anyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
        public string Dialect
        {
            get
            {
                return this.dialectField;
            }
            set
            {
                this.dialectField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://docs.oasis-open.org/wsn/b-2")]
    public partial class TopicExpressionType
    {
        
        private System.Xml.XmlNode[] anyField;
        
        private string dialectField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        [System.Xml.Serialization.XmlAnyElementAttribute(Order=0)]
        public System.Xml.XmlNode[] Any
        {
            get
            {
                return this.anyField;
            }
            set
            {
                this.anyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
        public string Dialect
        {
            get
            {
                return this.dialectField;
            }
            set
            {
                this.dialectField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.onvif.org/ver10/actionengine/wsdl")]
    public partial class ActionTriggerConfiguration
    {
        
        private TopicExpressionType topicExpressionField;
        
        private QueryExpressionType contentExpressionField;
        
        private string[] actionTokenField;
        
        private ActionTriggerConfigurationExtension extensionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public TopicExpressionType TopicExpression
        {
            get
            {
                return this.topicExpressionField;
            }
            set
            {
                this.topicExpressionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public QueryExpressionType ContentExpression
        {
            get
            {
                return this.contentExpressionField;
            }
            set
            {
                this.contentExpressionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ActionToken", Order=2)]
        public string[] ActionToken
        {
            get
            {
                return this.actionTokenField;
            }
            set
            {
                this.actionTokenField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public ActionTriggerConfigurationExtension Extension
        {
            get
            {
                return this.extensionField;
            }
            set
            {
                this.extensionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.onvif.org/ver10/actionengine/wsdl")]
    public partial class ActionTrigger
    {
        
        private ActionTriggerConfiguration configurationField;
        
        private System.Xml.XmlElement[] anyField;
        
        private string tokenField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public ActionTriggerConfiguration Configuration
        {
            get
            {
                return this.configurationField;
            }
            set
            {
                this.configurationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Order=1)]
        public System.Xml.XmlElement[] Any
        {
            get
            {
                return this.anyField;
            }
            set
            {
                this.anyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Token
        {
            get
            {
                return this.tokenField;
            }
            set
            {
                this.tokenField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.onvif.org/ver10/actionengine/wsdl")]
    public partial class ActionEngineCapabilitiesExtension
    {
        
        private System.Xml.XmlElement[] anyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Order=0)]
        public System.Xml.XmlElement[] Any
        {
            get
            {
                return this.anyField;
            }
            set
            {
                this.anyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.onvif.org/ver10/actionengine/wsdl")]
    public partial class ActionTypeLimits
    {
        
        private System.Xml.XmlElement[] anyField;
        
        private System.Xml.XmlQualifiedName typeField;
        
        private string maximumField;
        
        private string inUseField;
        
        public ActionTypeLimits()
        {
            this.inUseField = "0";
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Order=0)]
        public System.Xml.XmlElement[] Any
        {
            get
            {
                return this.anyField;
            }
            set
            {
                this.anyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.Xml.XmlQualifiedName Type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="positiveInteger")]
        public string Maximum
        {
            get
            {
                return this.maximumField;
            }
            set
            {
                this.maximumField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="nonNegativeInteger")]
        [System.ComponentModel.DefaultValueAttribute("0")]
        public string InUse
        {
            get
            {
                return this.inUseField;
            }
            set
            {
                this.inUseField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.onvif.org/ver10/actionengine/wsdl")]
    public partial class ActionEngineCapabilities
    {
        
        private ActionTypeLimits[] actionCapabilitiesField;
        
        private ActionEngineCapabilitiesExtension extensionField;
        
        private string maximumTriggersField;
        
        private string maximumActionsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ActionCapabilities", Order=0)]
        public ActionTypeLimits[] ActionCapabilities
        {
            get
            {
                return this.actionCapabilitiesField;
            }
            set
            {
                this.actionCapabilitiesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public ActionEngineCapabilitiesExtension Extension
        {
            get
            {
                return this.extensionField;
            }
            set
            {
                this.extensionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="positiveInteger")]
        public string MaximumTriggers
        {
            get
            {
                return this.maximumTriggersField;
            }
            set
            {
                this.maximumTriggersField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="positiveInteger")]
        public string MaximumActions
        {
            get
            {
                return this.maximumActionsField;
            }
            set
            {
                this.maximumActionsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.onvif.org/ver10/schema")]
    public partial class ItemListExtension
    {
        
        private System.Xml.XmlElement[] anyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Order=0)]
        public System.Xml.XmlElement[] Any
        {
            get
            {
                return this.anyField;
            }
            set
            {
                this.anyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.onvif.org/ver10/schema")]
    public partial class ItemList
    {
        
        private ItemListSimpleItem[] simpleItemField;
        
        private ItemListElementItem[] elementItemField;
        
        private ItemListExtension extensionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("SimpleItem", Order=0)]
        public ItemListSimpleItem[] SimpleItem
        {
            get
            {
                return this.simpleItemField;
            }
            set
            {
                this.simpleItemField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ElementItem", Order=1)]
        public ItemListElementItem[] ElementItem
        {
            get
            {
                return this.elementItemField;
            }
            set
            {
                this.elementItemField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public ItemListExtension Extension
        {
            get
            {
                return this.extensionField;
            }
            set
            {
                this.extensionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.onvif.org/ver10/schema")]
    public partial class ItemListSimpleItem
    {
        
        private string nameField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.onvif.org/ver10/schema")]
    public partial class ItemListElementItem
    {
        
        private System.Xml.XmlElement anyField;
        
        private string nameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Order=0)]
        public System.Xml.XmlElement Any
        {
            get
            {
                return this.anyField;
            }
            set
            {
                this.anyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.onvif.org/ver10/actionengine/wsdl")]
    public partial class ActionConfiguration
    {
        
        private ItemList parametersField;
        
        private System.Xml.XmlElement[] anyField;
        
        private string nameField;
        
        private System.Xml.XmlQualifiedName typeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public ItemList Parameters
        {
            get
            {
                return this.parametersField;
            }
            set
            {
                this.parametersField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Order=1)]
        public System.Xml.XmlElement[] Any
        {
            get
            {
                return this.anyField;
            }
            set
            {
                this.anyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.Xml.XmlQualifiedName Type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.onvif.org/ver10/actionengine/wsdl")]
    public partial class Action
    {
        
        private ActionConfiguration configurationField;
        
        private System.Xml.XmlElement[] anyField;
        
        private string tokenField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public ActionConfiguration Configuration
        {
            get
            {
                return this.configurationField;
            }
            set
            {
                this.configurationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Order=1)]
        public System.Xml.XmlElement[] Any
        {
            get
            {
                return this.anyField;
            }
            set
            {
                this.anyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Token
        {
            get
            {
                return this.tokenField;
            }
            set
            {
                this.tokenField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.onvif.org/ver10/actionengine/wsdl")]
    public partial class SupportedActionsExtension
    {
        
        private System.Xml.XmlElement[] anyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Order=0)]
        public System.Xml.XmlElement[] Any
        {
            get
            {
                return this.anyField;
            }
            set
            {
                this.anyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.onvif.org/ver10/schema")]
    public partial class ItemListDescriptionExtension
    {
        
        private System.Xml.XmlElement[] anyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Order=0)]
        public System.Xml.XmlElement[] Any
        {
            get
            {
                return this.anyField;
            }
            set
            {
                this.anyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.onvif.org/ver10/schema")]
    public partial class ItemListDescriptionElementItemDescription
    {
        
        private string nameField;
        
        private System.Xml.XmlQualifiedName typeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.Xml.XmlQualifiedName Type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetActions", WrapperNamespace="http://www.onvif.org/ver10/actionengine/wsdl", IsWrapped=true)]
    public partial class GetActionsRequest
    {
        
        public GetActionsRequest()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetActionsResponse", WrapperNamespace="http://www.onvif.org/ver10/actionengine/wsdl", IsWrapped=true)]
    public partial class GetActionsResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.onvif.org/ver10/actionengine/wsdl", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("Action")]
        public netOnvifCore.ActionEngine.Action[] Action;
        
        public GetActionsResponse()
        {
        }
        
        public GetActionsResponse(netOnvifCore.ActionEngine.Action[] Action)
        {
            this.Action = Action;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CreateActions", WrapperNamespace="http://www.onvif.org/ver10/actionengine/wsdl", IsWrapped=true)]
    public partial class CreateActionsRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.onvif.org/ver10/actionengine/wsdl", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("Action")]
        public netOnvifCore.ActionEngine.ActionConfiguration[] Action;
        
        public CreateActionsRequest()
        {
        }
        
        public CreateActionsRequest(netOnvifCore.ActionEngine.ActionConfiguration[] Action)
        {
            this.Action = Action;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CreateActionsResponse", WrapperNamespace="http://www.onvif.org/ver10/actionengine/wsdl", IsWrapped=true)]
    public partial class CreateActionsResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.onvif.org/ver10/actionengine/wsdl", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("Action")]
        public netOnvifCore.ActionEngine.Action[] Action;
        
        public CreateActionsResponse()
        {
        }
        
        public CreateActionsResponse(netOnvifCore.ActionEngine.Action[] Action)
        {
            this.Action = Action;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DeleteActions", WrapperNamespace="http://www.onvif.org/ver10/actionengine/wsdl", IsWrapped=true)]
    public partial class DeleteActionsRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.onvif.org/ver10/actionengine/wsdl", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("Token")]
        public string[] Token;
        
        public DeleteActionsRequest()
        {
        }
        
        public DeleteActionsRequest(string[] Token)
        {
            this.Token = Token;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DeleteActionsResponse", WrapperNamespace="http://www.onvif.org/ver10/actionengine/wsdl", IsWrapped=true)]
    public partial class DeleteActionsResponse
    {
        
        public DeleteActionsResponse()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ModifyActions", WrapperNamespace="http://www.onvif.org/ver10/actionengine/wsdl", IsWrapped=true)]
    public partial class ModifyActionsRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.onvif.org/ver10/actionengine/wsdl", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("Action")]
        public netOnvifCore.ActionEngine.Action[] Action;
        
        public ModifyActionsRequest()
        {
        }
        
        public ModifyActionsRequest(netOnvifCore.ActionEngine.Action[] Action)
        {
            this.Action = Action;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ModifyActionsResponse", WrapperNamespace="http://www.onvif.org/ver10/actionengine/wsdl", IsWrapped=true)]
    public partial class ModifyActionsResponse
    {
        
        public ModifyActionsResponse()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetActionTriggers", WrapperNamespace="http://www.onvif.org/ver10/actionengine/wsdl", IsWrapped=true)]
    public partial class GetActionTriggersRequest
    {
        
        public GetActionTriggersRequest()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetActionTriggersResponse", WrapperNamespace="http://www.onvif.org/ver10/actionengine/wsdl", IsWrapped=true)]
    public partial class GetActionTriggersResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.onvif.org/ver10/actionengine/wsdl", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("ActionTrigger")]
        public netOnvifCore.ActionEngine.ActionTrigger[] ActionTrigger;
        
        public GetActionTriggersResponse()
        {
        }
        
        public GetActionTriggersResponse(netOnvifCore.ActionEngine.ActionTrigger[] ActionTrigger)
        {
            this.ActionTrigger = ActionTrigger;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CreateActionTriggers", WrapperNamespace="http://www.onvif.org/ver10/actionengine/wsdl", IsWrapped=true)]
    public partial class CreateActionTriggersRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.onvif.org/ver10/actionengine/wsdl", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("ActionTrigger")]
        public netOnvifCore.ActionEngine.ActionTriggerConfiguration[] ActionTrigger;
        
        public CreateActionTriggersRequest()
        {
        }
        
        public CreateActionTriggersRequest(netOnvifCore.ActionEngine.ActionTriggerConfiguration[] ActionTrigger)
        {
            this.ActionTrigger = ActionTrigger;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CreateActionTriggersResponse", WrapperNamespace="http://www.onvif.org/ver10/actionengine/wsdl", IsWrapped=true)]
    public partial class CreateActionTriggersResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.onvif.org/ver10/actionengine/wsdl", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("ActionTrigger")]
        public netOnvifCore.ActionEngine.ActionTrigger[] ActionTrigger;
        
        public CreateActionTriggersResponse()
        {
        }
        
        public CreateActionTriggersResponse(netOnvifCore.ActionEngine.ActionTrigger[] ActionTrigger)
        {
            this.ActionTrigger = ActionTrigger;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DeleteActionTriggers", WrapperNamespace="http://www.onvif.org/ver10/actionengine/wsdl", IsWrapped=true)]
    public partial class DeleteActionTriggersRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.onvif.org/ver10/actionengine/wsdl", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("Token")]
        public string[] Token;
        
        public DeleteActionTriggersRequest()
        {
        }
        
        public DeleteActionTriggersRequest(string[] Token)
        {
            this.Token = Token;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DeleteActionTriggersResponse", WrapperNamespace="http://www.onvif.org/ver10/actionengine/wsdl", IsWrapped=true)]
    public partial class DeleteActionTriggersResponse
    {
        
        public DeleteActionTriggersResponse()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ModifyActionTriggers", WrapperNamespace="http://www.onvif.org/ver10/actionengine/wsdl", IsWrapped=true)]
    public partial class ModifyActionTriggersRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.onvif.org/ver10/actionengine/wsdl", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("ActionTrigger")]
        public netOnvifCore.ActionEngine.ActionTrigger[] ActionTrigger;
        
        public ModifyActionTriggersRequest()
        {
        }
        
        public ModifyActionTriggersRequest(netOnvifCore.ActionEngine.ActionTrigger[] ActionTrigger)
        {
            this.ActionTrigger = ActionTrigger;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ModifyActionTriggersResponse", WrapperNamespace="http://www.onvif.org/ver10/actionengine/wsdl", IsWrapped=true)]
    public partial class ModifyActionTriggersResponse
    {
        
        public ModifyActionTriggersResponse()
        {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public interface ActionEnginePortChannel : netOnvifCore.ActionEngine.ActionEnginePort, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public partial class ActionEnginePortClient : System.ServiceModel.ClientBase<netOnvifCore.ActionEngine.ActionEnginePort>, netOnvifCore.ActionEngine.ActionEnginePort
    {
        
        public ActionEnginePortClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<netOnvifCore.ActionEngine.SupportedActions> GetSupportedActionsAsync()
        {
            return base.Channel.GetSupportedActionsAsync();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<netOnvifCore.ActionEngine.GetActionsResponse> netOnvifCore.ActionEngine.ActionEnginePort.GetActionsAsync(netOnvifCore.ActionEngine.GetActionsRequest request)
        {
            return base.Channel.GetActionsAsync(request);
        }
        
        public System.Threading.Tasks.Task<netOnvifCore.ActionEngine.GetActionsResponse> GetActionsAsync()
        {
            netOnvifCore.ActionEngine.GetActionsRequest inValue = new netOnvifCore.ActionEngine.GetActionsRequest();
            return ((netOnvifCore.ActionEngine.ActionEnginePort)(this)).GetActionsAsync(inValue);
        }
        
        public System.Threading.Tasks.Task<netOnvifCore.ActionEngine.CreateActionsResponse> CreateActionsAsync(netOnvifCore.ActionEngine.CreateActionsRequest request)
        {
            return base.Channel.CreateActionsAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<netOnvifCore.ActionEngine.DeleteActionsResponse> netOnvifCore.ActionEngine.ActionEnginePort.DeleteActionsAsync(netOnvifCore.ActionEngine.DeleteActionsRequest request)
        {
            return base.Channel.DeleteActionsAsync(request);
        }
        
        public System.Threading.Tasks.Task<netOnvifCore.ActionEngine.DeleteActionsResponse> DeleteActionsAsync(string[] Token)
        {
            netOnvifCore.ActionEngine.DeleteActionsRequest inValue = new netOnvifCore.ActionEngine.DeleteActionsRequest();
            inValue.Token = Token;
            return ((netOnvifCore.ActionEngine.ActionEnginePort)(this)).DeleteActionsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<netOnvifCore.ActionEngine.ModifyActionsResponse> netOnvifCore.ActionEngine.ActionEnginePort.ModifyActionsAsync(netOnvifCore.ActionEngine.ModifyActionsRequest request)
        {
            return base.Channel.ModifyActionsAsync(request);
        }
        
        public System.Threading.Tasks.Task<netOnvifCore.ActionEngine.ModifyActionsResponse> ModifyActionsAsync(netOnvifCore.ActionEngine.Action[] Action)
        {
            netOnvifCore.ActionEngine.ModifyActionsRequest inValue = new netOnvifCore.ActionEngine.ModifyActionsRequest();
            inValue.Action = Action;
            return ((netOnvifCore.ActionEngine.ActionEnginePort)(this)).ModifyActionsAsync(inValue);
        }
        
        public System.Threading.Tasks.Task<netOnvifCore.ActionEngine.ActionEngineCapabilities> GetServiceCapabilitiesAsync()
        {
            return base.Channel.GetServiceCapabilitiesAsync();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<netOnvifCore.ActionEngine.GetActionTriggersResponse> netOnvifCore.ActionEngine.ActionEnginePort.GetActionTriggersAsync(netOnvifCore.ActionEngine.GetActionTriggersRequest request)
        {
            return base.Channel.GetActionTriggersAsync(request);
        }
        
        public System.Threading.Tasks.Task<netOnvifCore.ActionEngine.GetActionTriggersResponse> GetActionTriggersAsync()
        {
            netOnvifCore.ActionEngine.GetActionTriggersRequest inValue = new netOnvifCore.ActionEngine.GetActionTriggersRequest();
            return ((netOnvifCore.ActionEngine.ActionEnginePort)(this)).GetActionTriggersAsync(inValue);
        }
        
        public System.Threading.Tasks.Task<netOnvifCore.ActionEngine.CreateActionTriggersResponse> CreateActionTriggersAsync(netOnvifCore.ActionEngine.CreateActionTriggersRequest request)
        {
            return base.Channel.CreateActionTriggersAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<netOnvifCore.ActionEngine.DeleteActionTriggersResponse> netOnvifCore.ActionEngine.ActionEnginePort.DeleteActionTriggersAsync(netOnvifCore.ActionEngine.DeleteActionTriggersRequest request)
        {
            return base.Channel.DeleteActionTriggersAsync(request);
        }
        
        public System.Threading.Tasks.Task<netOnvifCore.ActionEngine.DeleteActionTriggersResponse> DeleteActionTriggersAsync(string[] Token)
        {
            netOnvifCore.ActionEngine.DeleteActionTriggersRequest inValue = new netOnvifCore.ActionEngine.DeleteActionTriggersRequest();
            inValue.Token = Token;
            return ((netOnvifCore.ActionEngine.ActionEnginePort)(this)).DeleteActionTriggersAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<netOnvifCore.ActionEngine.ModifyActionTriggersResponse> netOnvifCore.ActionEngine.ActionEnginePort.ModifyActionTriggersAsync(netOnvifCore.ActionEngine.ModifyActionTriggersRequest request)
        {
            return base.Channel.ModifyActionTriggersAsync(request);
        }
        
        public System.Threading.Tasks.Task<netOnvifCore.ActionEngine.ModifyActionTriggersResponse> ModifyActionTriggersAsync(netOnvifCore.ActionEngine.ActionTrigger[] ActionTrigger)
        {
            netOnvifCore.ActionEngine.ModifyActionTriggersRequest inValue = new netOnvifCore.ActionEngine.ModifyActionTriggersRequest();
            inValue.ActionTrigger = ActionTrigger;
            return ((netOnvifCore.ActionEngine.ActionEnginePort)(this)).ModifyActionTriggersAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
    }
}
